/*
 *  Copyright (C) 2010 Le Tuan Anh <tuananh.ke@gmail.com>
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * StaticTextStep.java
 *
 * Created on Jan 24, 2010, 11:19:00 AM
 */
package org.dakside.duck.demo.plugins.wizards;

import org.dakside.duck.dakwizard.AbstractWizardStep;
import javax.swing.Icon;

/**
 * A sample static step (does not require focus)
 * @author LeTuanAnh <tuananh.ke@gmail.com>
 */
public class StaticTextStep extends AbstractWizardStep<NewUserWizardModel> {

    /** Creates new form StaticTextStep
     * @param model
     * @param image
     * @param text */
    public StaticTextStep(NewUserWizardModel model, Icon image, String text) {
        super(model, false);
        initComponents();
        if (image == null) {
            imageBox.setVisible(false);
        } else {
            imageBox.setIcon(image);

        }
        txtStaticText.setText(text);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageBox = new javax.swing.JLabel();
        txtStaticText = new javax.swing.JLabel();

        imageBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtStaticText.setText("jLabel2");
        txtStaticText.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        txtStaticText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStaticText, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStaticText, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(imageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageBox;
    private javax.swing.JLabel txtStaticText;
    // End of variables declaration//GEN-END:variables

    public boolean isCancellable() {
        return true;
    }

    public boolean isFinishable() {
        return getNextStep() == null;
    }

    @Override
    public boolean canGoNext() {
        return true;
    }

    @Override
    public boolean canGoBack() {
        return true;
    }
}
